# Local database for testing
# docker swarm init   # If not already in a swarm
# docker stack deploy -c stack.yml postgres
version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: api
    ports:
      - 5432:5432
    networks:
      - overlay

  adminer:
    image: adminer
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 8080:8080
    networks:
      - overlay

volumes:
  db-data:

networks:
  overlay:
